spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/defi
    username: defi_app
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/migrations/changelog.xml
    enabled: true

server:
  port: 8080
